#-------------------------------------------------------------------------
# About section 

aboutPhotos:
- name: 'group1.jpg'
  order: 'first'
- name: 'group2.jpg'
  order: 'second'
- name: 'group3.jpg'
  order: 'third'

#-------------------------------------------------------------------------
# Work section 

projects:
- name: 'Corporate'
  order: 'first'
  text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
  Aenean commodo ligula eget dolor. Aenean massa. 
  Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
- name: 'Fictions'
  order: 'second'
  text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
  Aenean commodo ligula eget dolor. Aenean massa. 
  Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'
  - name: 'Documentaries'
    order: 'third'
    text: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
    Aenean commodo ligula eget dolor. Aenean massa. 
    Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.'  